# Generated by Django 4.2.1 on 2023-10-04 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_related_files_alter_post_related_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='related_images',
        ),
        migrations.DeleteModel(
            name='RelatedImage',
        ),
    ]
