# Generated by Django 4.2.1 on 2023-10-04 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_remove_post_related_images_delete_relatedimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='related_files',
        ),
        migrations.AddField(
            model_name='relatedfile',
            name='related_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relatedFile_post', to='posts.post'),
        ),
    ]
