# Generated by Django 4.2.1 on 2023-10-04 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_postcomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postcomment',
            old_name='post_comment',
            new_name='post',
        ),
    ]
