# Generated by Django 4.2.6 on 2023-10-05 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GroupPosts', '0003_grouppost_post_status'),
        ('posts', '0007_alter_post_user_alter_postcomment_comment_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatedfile',
            name='related_GroupPost',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relatedFile_grouppost', to='GroupPosts.grouppost'),
        ),
    ]
