# Generated by Django 4.2.6 on 2023-10-12 19:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0009_postsrating'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postLike_user', to=settings.AUTH_USER_MODEL)),
                ('post_liked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postLike_post', to='posts.post')),
            ],
        ),
    ]
