# Generated by Django 4.2.1 on 2023-10-02 21:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creategroup',
            old_name='user',
            new_name='admin',
        ),
        migrations.AddField(
            model_name='creategroup',
            name='members',
            field=models.ManyToManyField(related_name='members_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='creategroup',
            name='title',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
