# Generated by Django 4.2.6 on 2023-10-05 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GroupPosts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grouppost',
            old_name='user',
            new_name='post_by',
        ),
    ]
