# Generated by Django 4.2.6 on 2023-10-05 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GroupPosts', '0002_rename_user_grouppost_post_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouppost',
            name='post_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approve', 'Approve'), ('Decline', 'Decline')], default='Pending', max_length=30),
        ),
    ]
