# Generated by Django 4.2.6 on 2023-10-12 22:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0002_rename_user_creategroup_admin_creategroup_members_and_more'),
        ('GroupPosts', '0003_grouppost_post_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupPostLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likedPost_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postLiked_group', to='groups.creategroup')),
                ('liked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_postLike_user', to=settings.AUTH_USER_MODEL)),
                ('post_liked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postLike_groupPost', to='GroupPosts.grouppost')),
            ],
        ),
    ]
