# Generated by Django 4.2.6 on 2023-10-13 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GroupPosts', '0005_grouppostcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouppostcomment',
            name='time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
