# Generated by Django 4.2.6 on 2023-10-13 00:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('GroupPosts', '0007_alter_grouppostcomment_comment_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouppostcomment',
            name='comment_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postComment_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
